### ISSUE TITLE
Modal upload form

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#18]
This issue is to organize standing issues with the modal upload form.
- schools search doesn't suggest creating new school, or say a school is not found
- courses search doesn't show searched courses
- courses search doesn't suggest creating new courses
- Form should be pre-populated when clicking UPLOAD from an enrolled course

**Comment by sethwoodworth** [comment]
cc @OnlyInAmerica so you can follow along

**Comment by sethwoodworth** [comment]
The course autocomplete search endpoint errors with 

```
ERROR:django.request:Internal Server Error: /courses
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/seth/code/djKarma/notes/views.py", line 415, in courses
    courses = Course.objects.filter(title__icontains=query, school=School.objects.get(pk=school_pk)).d
istinct()
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 358, in get
    clone = self.filter(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 621, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 639, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    can_reuse=used_aliases, force_having=force_having)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1185, in add_filter
    connector)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/where.py", line 69, in add
    value = obj.prepare(lookup_type, value)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/where.py", line 320, in prepare
    return self.field.get_prep_lookup(lookup_type, value)
  File "/usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 310, in get_prep_l
ookup
    return self.get_prep_value(value)
  File "/usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 537, in get_prep_v
alue
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[08/Aug/2012 15:15:09] "GET /courses?school=&q=und HTTP/1.1" 500 14766
```

**Comment by sethwoodworth** [comment]
this issue has been replaced with #25 and most things in this list have been completed.
